logging:
  level:
    ROOT: INFO
    org.hibernate: INFO

# ssl configs
server:
  port: 65443
  ssl:
    # key-store for ssl only
    enabled: true
    key-store: '/Users/bishop/Articles/Demo-Projects/certs/ssl/keystore-my-application.p12'
    key-store-password: 'changeit!'
    key-store-type: PKCS12
    key-alias: 'ssl'

  # trust-store containing channel-service certificate for signature verification
  verification:
    trust-store: '/Users/bishop/Articles/Demo-Projects/certs/verification/truststore-channel-service.p12'
    trust-store-password: 'channel-verify!'
    trust-store-type: PKCS12
    trust-alias: 'verify'