logging:
  level:
    ROOT: INFO
    org.hibernate: INFO

# ssl configs
server:
  port: 51443
  ssl:
    # key-store for ssl only
    enabled: true
    key-store: '/Users/bishop/Articles/Demo-Projects/certs/ssl/keystore-my-application.p12'
    key-store-password: 'changeit!'
    key-store-type: PKCS12
    key-alias: 'ssl'

# HS256 (symmetric) jwt secret key, base64 encoded: Symmetric - The same secret key is used for both signing and verification
jwt:
  secret: "WHg5JGtMcDcjMmdUIXdNelZiTjRxWUBlRnUxekhyTGQ="